version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pdepratico-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pdepratico
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pdepratico-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdepratico-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pdepratico-network

volumes:
  postgres-data:

networks:
  pdepratico-network:
